homepage: https://turfjs.org/
language: javascript
main_repo: https://github.com/Turfjs/turf
fuzzing_engines:
- libfuzzer
sanitizers:
- none
vendor_ccs:
- yakdan@code-intelligence.com
- norbert.schneider@code-intelligence.com
- peter.samarin@code-intelligence.com
- christopher.krah@code-intelligence.com
